In [1]:
print("hii")

hii


In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 2.4 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.8 MB 2.0 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.8 MB 1.6 MB/s eta 0:00:08
   ---- ----------------------------------- 1.6/12.8 MB 1.6 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.8 MB 1.8 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.8 MB 1.9 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.8 MB 2.0 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.8 MB 2.2 MB/s eta 0:00:05
   --------------- ------------------------ 5.0/12.8 MB 2.5 MB/s eta 0:00:04
   ------------------ --------------------- 6.0/12.8 MB 2.7 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.8 MB 2.8 MB/s eta 0:00:03
   ----------

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [30]:
arr2=np.array([[[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]],[[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]]])
print(arr2)
print(type(arr2))
print(arr2.shape)


[[[[1 2]
   [2 3]
   [3 4]]

  [[1 2]
   [2 3]
   [3 4]]]


 [[[1 2]
   [2 3]
   [3 4]]

  [[1 2]
   [2 3]
   [3 4]]]]
<class 'numpy.ndarray'>
(2, 2, 3, 2)


In [ ]:
arr3=np.array([1,2,3,4,5,6])
print(arr3)
print(arr3.shape)
arr4=arr3.reshape(2,3)
print(arr4)
print(arr4.shape)
print(arr2.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'tuple'>


In [21]:
np.arange(0,10,3).reshape(2,2)

array([[0, 3],
       [6, 9]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Attributes of numpy array

In [69]:
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)
print(arr.itemsize)
print(arr2.shape)

1
5
int64
8
(5,)


Vectorised Operations

In [35]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


Universal Functions

In [ ]:
arr=np.array([1,4,9,16,25,90])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         2.         3.         4.         5.         9.48683298
 3.16227766]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 1.22040329e+39 2.20264658e+04]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175  0.89399666
 -0.54402111]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 4.49980967
 2.30258509]


Array slicing and indexing

In [55]:
arr=np.array([[1,2,3,4],[3,4,5,6],[3,2,5,4]]);
print(arr)
print(arr[0][0],"\n")
print(arr[0,3],"\n")
print(arr[1:3,1:3],"\n")
print(arr[1:,2:])

arr[0,0]=100
print(arr)
arr[1:2,1:3]=100
print(arr)


[[1 2 3 4]
 [3 4 5 6]
 [3 2 5 4]]
1 

4 

[[4 5]
 [2 5]] 

[[5 6]
 [5 4]]
[[100   2   3   4]
 [  3   4   5   6]
 [  3   2   5   4]]
[[100   2   3   4]
 [  3 100 100   6]
 [  3   2   5   4]]


Normalization

In [57]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print("Normalized data: ",normalized_data)
print(data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[1 2 3 4 5]


In [58]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(data)
std_dev=np.std(data)
median=np.median(data)
var=np.var(data)
print(mean,median,var,std_dev)

5.5 5.5 8.25 2.8722813232690143


In [67]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
x=(data>5) 

new=np.array([1,2,3,4,5,6,7,8,9,2])
n=new[x]
print(x)
print(n)

[False False False False False  True  True  True  True  True]
[6 7 8 9 2]


In [68]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
x=(data>5) & (data<=8)
new=np.array([1,2,3,4,5,6,7,8,9,2])
n=new[x]
print(x)
print(n)

[False False False False False  True  True  True False False]
[6 7 8]


In [83]:
arr=np.array(["apple","mango","banana",5])
print(arr)
print(type(arr))

['apple' 'mango' 'banana' '5']
<class 'numpy.ndarray'>
